/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 *
 */
package l2e.gameserver.model.base;

public enum BonusType
{
	EXP,
	SP,
	FISHING,
	SIEGE,
	ELEMENT_STONE,
	SEAL_STONE,
	QUEST_REWARD,
	QUEST_DROP,
	QUEST_ADENA,
	DROP_ITEMS,
	DROP_ADENA,
	DROP_RAID,
	DROP_EPIC,
	SPOIL,
	WEIGHT,
	FAME,
	REFLECTION_REDUCE,
	EVENTS,
	CRAFT_CHANCE,
	MASTER_WORK_CHANCE,
	ENCHANT_CHANCE,
	NOBLE_STONE_MIN_AMOUNT,
	SEAL_STONE_MIN_AMOUNT,
	LIFE_STONE_MIN_AMOUNT,
	ENCHANT_SCROLL_MIN_AMOUNT,
	FORGOTTEN_SCROLL_MIN_AMOUNT,
	MATERIAL_MIN_AMOUNT,
	RECIPE_MIN_AMOUNT,
	BELT_MIN_AMOUNT,
	BRACLET_MIN_AMOUNT,
	CLOAK_MIN_AMOUNT,
	CODEX_BOOK_MIN_AMOUNT,
	ATT_STONE_MIN_AMOUNT,
	ATT_CRYSTAL_MIN_AMOUNT,
	ATT_JEWEL_MIN_AMOUNT,
	ATT_ENERGY_MIN_AMOUNT,
	WEAPON_MIN_AMOUNT,
	ARMOR_MIN_AMOUNT,
	ACCESSORY_MIN_AMOUNT,
	NOBLE_STONE_MAX_AMOUNT,
	SEAL_STONE_MAX_AMOUNT,
	LIFE_STONE_MAX_AMOUNT,
	ENCHANT_SCROLL_MAX_AMOUNT,
	FORGOTTEN_SCROLL_MAX_AMOUNT,
	MATERIAL_MAX_AMOUNT,
	RECIPE_MAX_AMOUNT,
	BELT_MAX_AMOUNT,
	BRACLET_MAX_AMOUNT,
	CLOAK_MAX_AMOUNT,
	CODEX_BOOK_MAX_AMOUNT,
	ATT_STONE_MAX_AMOUNT,
	ATT_CRYSTAL_MAX_AMOUNT,
	ATT_JEWEL_MAX_AMOUNT,
	ATT_ENERGY_MAX_AMOUNT,
	WEAPON_MAX_AMOUNT,
	ARMOR_MAX_AMOUNT,
	ACCESSORY_MAX_AMOUNT,
	MAX_SPOIL_PER_ONE_GROUP,
	MAX_DROP_PER_ONE_GROUP,
	MAX_RAID_DROP_PER_ONE_GROUP,
	GROUP_RATE;
}